name: polyolefin_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  # 仅通过 conda 安装 RDKit
  - rdkit
  
  # 其余库通过 pip 安装
  - pip
  - pip:
    - streamlit
    - pandas
    - numpy
    - scikit-learn
    - joblib
    - matplotlib
    - seaborn
