name: polyolefin_env
channels:
  - conda-forge
dependencies:
  - python=3.13.5
  # 使用 conda-forge 安装 RDKit，这是最可靠的方式
  - rdkit
  
  # 其他需要通过 conda 安装的库（可选，如果 pip 失败）
  # - numpy
  # - pandas

  - pip
  - pip:
    # 将其余所有库放回 pip 列表
    - streamlit
    - pandas
    - numpy
    - scikit-learn
    - joblib
    - matplotlib
    - seaborn
